# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities



driver = webdriver.Chrome()
vars = {}
  
 # Test name: 1
  # Step # | name | target | value
  # 1 | open | /monitor/monclassic.html?bts=2024-09-27-09_50_40 | 
  driver.get("https://192.168.17.227/monitor/monclassic.html?bts=2024-09-27-09_50_40")
    # 2 | setWindowSize | 1854x1011 | 
  driver.set_window_size(1854, 1011)
    # 3 | click | id=dev1stadmstate | 
  driver.find_element(By.ID, "dev1stadmstate").click()
    # 4 | click | id=ui-id-25 | 
  driver.find_element(By.ID, "ui-id-25").click()
    # 5 | click | css=#dev1_Ln1TxEnable .on-click-edit | 
  driver.find_element(By.CSS_SELECTOR, "#dev1_Ln1TxEnable .on-click-edit").click()
    # 6 | click | css=.ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
  driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
    # 7 | click | css=.ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
  driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
    # 8 | click | id=dev1st___cls | 
  driver.find_element(By.ID, "dev1st___cls").click()
    # 9 | click | css=#dev1_Ln2TxEnable .on-click-edit | 
  driver.find_element(By.CSS_SELECTOR, "#dev1_Ln2TxEnable .on-click-edit").click()
    # 10 | click | css=.ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
  driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
    # 11 | click | css=.ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
  driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
  
