# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1(self):
    # Test name: 1
    # Step # | name | target | value
    # 1 | open | /monitor/monclassic.html?bts=2024-09-27-09_50_40 | 
    self.driver.get("https://192.168.17.227/monitor/monclassic.html?bts=2024-09-27-09_50_40")
    # 2 | setWindowSize | 1854x1011 | 
    self.driver.set_window_size(1854, 1011)
    # 3 | click | id=dev1stadmstate | 
    self.driver.find_element(By.ID, "dev1stadmstate").click()
    # 4 | click | id=ui-id-25 | 
    self.driver.find_element(By.ID, "ui-id-25").click()
    # 5 | click | css=#dev1_Ln1PortState .on-click-edit | 
    self.driver.find_element(By.CSS_SELECTOR, "#dev1_Ln1PortState .on-click-edit").click()
    # 6 | select | id=param_select_value | label=OOS-MT
    dropdown = self.driver.find_element(By.ID, "param_select_value")
    dropdown.find_element(By.XPATH, "//option[. = 'OOS-MT']").click()
    # 7 | click | css=.ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
    # 8 | click | css=.ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
    # 9 | click | css=#dev1_Ln2PortState .on-click-edit | 
    self.driver.find_element(By.CSS_SELECTOR, "#dev1_Ln2PortState .on-click-edit").click()
    # 10 | select | id=param_select_value | label=OOS-MT
    dropdown = self.driver.find_element(By.ID, "param_select_value")
    dropdown.find_element(By.XPATH, "//option[. = 'OOS-MT']").click()
    # 11 | click | css=.ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
    # 12 | click | css=.ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
    # 13 | click | css=#dev1_Ln1PortState .on-click-edit | 
    self.driver.find_element(By.CSS_SELECTOR, "#dev1_Ln1PortState .on-click-edit").click()
    # 14 | select | id=param_select_value | label=OOS
    dropdown = self.driver.find_element(By.ID, "param_select_value")
    dropdown.find_element(By.XPATH, "//option[. = 'OOS']").click()
    # 15 | click | css=.ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
    # 16 | click | css=.ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
    # 17 | click | css=#dev1_Ln2PortState .on-click-edit | 
    self.driver.find_element(By.CSS_SELECTOR, "#dev1_Ln2PortState .on-click-edit").click()
    # 18 | select | id=param_select_value | label=OOS
    dropdown = self.driver.find_element(By.ID, "param_select_value")
    dropdown.find_element(By.XPATH, "//option[. = 'OOS']").click()
    # 19 | mouseDownAt | id=param_select_value | -0.171875,-0.84375
    element = self.driver.find_element(By.ID, "param_select_value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 20 | mouseMoveAt | id=param_select_value | -0.171875,-0.84375
    element = self.driver.find_element(By.ID, "param_select_value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 21 | mouseUpAt | id=param_select_value | -0.171875,-0.84375
    element = self.driver.find_element(By.ID, "param_select_value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 22 | click | css=.ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
    # 23 | click | css=.ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
    # 24 | click | css=#dev1_Cl1PortState .on-click-edit | 
    self.driver.find_element(By.CSS_SELECTOR, "#dev1_Cl1PortState .on-click-edit").click()
    # 25 | select | id=param_select_value | label=OOS-MT
    dropdown = self.driver.find_element(By.ID, "param_select_value")
    dropdown.find_element(By.XPATH, "//option[. = 'OOS-MT']").click()
    # 26 | mouseDownAt | id=param_select_value | -0.171875,-0.328125
    element = self.driver.find_element(By.ID, "param_select_value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 27 | mouseMoveAt | id=param_select_value | -0.171875,-0.328125
    element = self.driver.find_element(By.ID, "param_select_value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 28 | mouseUpAt | id=param_select_value | -0.171875,-0.328125
    element = self.driver.find_element(By.ID, "param_select_value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 29 | click | css=.ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
    # 30 | click | css=.ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
    # 31 | click | css=#dev1_Cl1PortState .on-click-edit | 
    self.driver.find_element(By.CSS_SELECTOR, "#dev1_Cl1PortState .on-click-edit").click()
    # 32 | select | id=param_select_value | label=OOS
    dropdown = self.driver.find_element(By.ID, "param_select_value")
    dropdown.find_element(By.XPATH, "//option[. = 'OOS']").click()
    # 33 | mouseDownAt | id=param_select_value | -0.171875,-0.34375
    element = self.driver.find_element(By.ID, "param_select_value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 34 | mouseMoveAt | id=param_select_value | -0.171875,-0.34375
    element = self.driver.find_element(By.ID, "param_select_value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 35 | mouseUpAt | id=param_select_value | -0.171875,-0.34375
    element = self.driver.find_element(By.ID, "param_select_value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 36 | click | css=.ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(15) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
    # 37 | click | css=.ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(18) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
  
