# Generated by Selenium IDE
import os
import sys
import time
import logging
from datetime import datetime
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from fpdf import FPDF


logging.basicConfig(level=logging.DEBUG)

options = webdriver.ChromeOptions()
service = Service('/usr/bin/chromedriver' , log_path='/tmp/chromedriver.log')  # Путь к chromedriver
options.binary_location =  '/usr/bin/chromium-browser'  # Путь к браузеру Chrome
driver = webdriver.Chrome(service=service, options=options)

sys.stdout = open('logging_tabs_test_blades.txt','w')

  #СОЗДАЕМ ФУНКЦИИ ДЛЯ СОЗДАНИЯ СКРИНШОТОВ И ПЕРЕНОСА ИХ PDF-ФАЙЛ

def take_screenshot(driver, test_name):
    """Сохраняет скриншот текущей страницы в указанную папку."""
    # Создаем папку для скриншотов, если она не существует
    screenshot_dir = 'screenshots'
    os.makedirs(screenshot_dir, exist_ok=True)

    # Генерируем имя файла с временной меткой
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_filename = f"{screenshot_dir}/{test_name}_screenshot_{timestamp}.png"
    
    # Сохраняем скриншот
    driver.save_screenshot(output_filename)
    print(f"Screenshot saved to {output_filename}")
    return output_filename
    
def create_pdf_from_images(image_paths, pdf_filename):
    """Создает PDF-файл из списка изображений."""
    pdf = FPDF()
    for image_path in image_paths:
        pdf.add_page()
        pdf.image(image_path, x=10, y=10, w=190)
    pdf.output(pdf_filename)
    print(f"PDF saved to {pdf_filename}")



  #ПЕРЕХОД НА WEB-ИНТЕРФЕЙС
try:
  screenshot_paths = []
  driver.get("http://192.168.17.223/monitor/monclassic.html?bts=2023-11-09-16_13_32&debug=true")
  driver.set_window_size(1854, 1011)
  time.sleep(3)
  driver.find_element(By.ID, "login").send_keys("Admin")
  time.sleep(3)
  driver.find_element(By.ID, "password").click()
  time.sleep(3)
  driver.find_element(By.ID, "password").send_keys("cradmin")
  driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(8) > .ui-dialog-buttonpane .ui-button").click()
  time.sleep(6)
  driver.find_element(By.ID, "dev6stadmstate").click()
  time.sleep(3)
  print("Переход на страницу и авторизация:ОК")
except Exception as e:
    print("Переход на страницу и авторизация:ERROR")
    

  #ПРОВЕРКА ФУНКЦИОНАЛА КНОПОК ВКЛАДКИ "ПОЛЬЗОВАТЕЛЬ"
try:
  driver.find_element(By.LINK_TEXT, "Пользователи").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, ".bg_page").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, ".user-element:nth-child(1) .on-click-view-session-permissions").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(24) > .ui-dialog-buttonpane .ui-button").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, ".user-element:nth-child(2) .on-click-set-permissions").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(19) .ui-button:nth-child(1)").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, ".user-element:nth-child(3) .on-click-set-passexp").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(24) > .ui-dialog-buttonpane .ui-button").click()
  time.sleep(3)
  screenshot_paths.append(take_screenshot(driver, "1"))
  time.sleep(1)
  print("Вкладка 'Пользователь':ОК")
except Exception as e:
    print("Вкладка 'Пользователь':ERROR")
    
    
  #ТАБЛИЦА ВКЛАДКИ "ПОКАЗАТЕЛИ КАЧЕСТВА"
try:
  driver.find_element(By.LINK_TEXT, "Показатели качества").click()
  time.sleep(3)
  driver.find_element(By.ID, "slot").click()
  time.sleep(3)
  dropdown = driver.find_element(By.ID, "slot")
  dropdown.find_element(By.XPATH, "//option[. = '6 / engn-4.0.0 / QUASAR-TP']").click()
  time.sleep(3)
  element = driver.find_element(By.ID, "slot")
  actions = ActionChains(driver)
  actions.move_to_element(element).click_and_hold().perform()
  time.sleep(3)
  element = driver.find_element(By.ID, "slot")
  actions = ActionChains(driver)
  actions.move_to_element(element).perform()
  time.sleep(3)
  element = driver.find_element(By.ID, "slot")
  actions = ActionChains(driver)
  actions.move_to_element(element).release().perform()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, ".ui-button:nth-child(7)").click()
  time.sleep(3)
  screenshot_paths.append(take_screenshot(driver, "2"))
  time.sleep(1)
  print("Таблица 'Показатели качества':ОК")
except Exception as e:
    print("Таблица 'Показатели качества':ERROR")
    
  #РЕЗЕРВИРОВАНИЕ КОПИИ КОНФИГУРАЦИИ ПАРАМЕТРОВ
try:
  driver.find_element(By.ID, "bkpmark").click()
  time.sleep(3)
  driver.find_element(By.ID, "upload_backups_button").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(12) .ui-button-icon").click()
  time.sleep(3)
  screenshot_paths.append(take_screenshot(driver, "3"))
  time.sleep(1)
  print("Вкладка 'Резервирование':ОК")
except Exception as e:
    print("Вкладка 'Резервирование':ERROR")

  #ПО БЛОКА УПРАВЛЕНИЯ ВО ВКЛАДКЕ "УПРАВЛЕНИЕ"
try:
  driver.find_element(By.ID, "updmark").click()
  time.sleep(3)
  screenshot_paths.append(take_screenshot(driver, "4"))
  time.sleep(1)
  print("Вкладка 'ПО блока управления':ОК")
except Exception as e:
    print("Вкладка 'ПО блока управления':ERROR")
    
  #УПРАВЛЕНИЕ УСТРОЙСТВАМИ ВО ВКЛАДКЕ "УПРАВЛЕНИЕ"
try:
  driver.find_element(By.ID, "ui-id-11").click()
  time.sleep(3)
  screenshot_paths.append(take_screenshot(driver, "5"))
  time.sleep(1)
  print("Вкладка 'Управление устройствами':ОК")
except Exception as e:
    print("Вкладка 'Управление устройствами':ERROR")
    
  #УПРАВЛЕНИЕ СЕРТИФИКАТАМИ ВО ВКЛАДКЕ "УПРАВЛЕНИЕ"
try:
  driver.find_element(By.ID, "ui-id-12").click()
  time.sleep(3)
  screenshot_paths.append(take_screenshot(driver, "6"))
  time.sleep(1)
  print("Вкладка 'Управлени сертификатами':ОК")
except Exception as e:
    print("Вкладка 'Управление сертификатами':ERROR")
    
  #МЕЖСЕТЕВОЙ ЭКРАН ВО ВКЛАДКЕ "УПРАВЛЕНИЕ"
try:
  driver.find_element(By.ID, "ui-id-13").click()
  time.sleep(3)
  screenshot_paths.append(take_screenshot(driver, "7"))
  time.sleep(1)
  print("Вкладка 'Межсетевой экран':ОК")
except Exception as e:
    print("Вкладка 'Межсетевой экран':ERROR")

  #СОЗДАНИЕ СЛЕПКА ВО ВКЛАДКЕ "УПРАВЛЕНИЕ"
try:
  driver.find_element(By.ID, "ui-id-14").click()
  time.sleep(3)
  screenshot_paths.append(take_screenshot(driver, "8"))
  time.sleep(1)
  print("Вкладка 'Создание слепка':ОК")
except Exception as e:
    print("Вкладка 'Создание слепка':ERROR")
    
  #ПЕРЕХОД НА ВКЛАДКУ "МАСКИРОВАНИЕ" И ВЗАИМОДЕЙСТВИЕ С НЕЙ
try:
  driver.find_element(By.LINK_TEXT, "Маскирование").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, ".param-element:nth-child(22) .on-click-edit-pm").click()
  dropdown = driver.find_element(By.ID, "pm_choice")
  time.sleep(3)
  dropdown.find_element(By.XPATH, "//option[. = 'Да']").click()
  element = driver.find_element(By.ID, "pm_choice")
  actions = ActionChains(driver)
  actions.move_to_element(element).click_and_hold().perform()
  element = driver.find_element(By.ID, "pm_choice")
  time.sleep(3)
  actions = ActionChains(driver)
  actions.move_to_element(element).perform()
  element = driver.find_element(By.ID, "pm_choice")
  actions = ActionChains(driver)
  actions.move_to_element(element).release().perform()
  driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(12) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, ".param-element:nth-child(23) .on-click-edit-pm").click()
  dropdown = driver.find_element(By.ID, "pm_choice")
  time.sleep(3)
  dropdown.find_element(By.XPATH, "//option[. = 'Да']").click()
  element = driver.find_element(By.ID, "pm_choice")
  actions = ActionChains(driver)
  actions.move_to_element(element).click_and_hold().perform()
  element = driver.find_element(By.ID, "pm_choice")
  time.sleep(3)
  actions = ActionChains(driver)
  actions.move_to_element(element).perform()
  element = driver.find_element(By.ID, "pm_choice")
  actions = ActionChains(driver)
  actions.move_to_element(element).release().perform()
  driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(12) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, ".param-element:nth-child(22) .on-click-edit-pm").click()
  dropdown = driver.find_element(By.ID, "pm_choice")
  time.sleep(3)
  dropdown.find_element(By.XPATH, "//option[. = 'Нет']").click()
  element = driver.find_element(By.ID, "pm_choice")
  actions = ActionChains(driver)
  actions.move_to_element(element).click_and_hold().perform()
  element = driver.find_element(By.ID, "pm_choice")
  time.sleep(3)
  actions = ActionChains(driver)
  actions.move_to_element(element).perform()
  element = driver.find_element(By.ID, "pm_choice")
  actions = ActionChains(driver)
  actions.move_to_element(element).release().perform()
  driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(12) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, ".param-element:nth-child(23) .on-click-edit-pm").click()
  dropdown = driver.find_element(By.ID, "pm_choice")
  time.sleep(3)
  dropdown.find_element(By.XPATH, "//option[. = 'Нет']").click()
  element = driver.find_element(By.ID, "pm_choice")
  actions = ActionChains(driver)
  actions.move_to_element(element).click_and_hold().perform()
  element = driver.find_element(By.ID, "pm_choice")
  actions = ActionChains(driver)
  actions.move_to_element(element).perform()
  element = driver.find_element(By.ID, "pm_choice")
  time.sleep(3)
  actions = ActionChains(driver)
  actions.move_to_element(element).release().perform()
  driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(12) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
  time.sleep(3)
  screenshot_paths.append(take_screenshot(driver, "9"))
  time.sleep(3)
  print("Вкладка 'Маскирование':ОК")
except Exception as e:
    print("Вкладка 'Маскирование':ERROR")
    
  #ПЕРЕХОД НА ВКЛАДКУ "ЖУРНАЛ"/ВЫБОР ДАТЫ И СРАВНЕНИЕ ВРЕМЕНИ UTC
try:
  driver.find_element(By.LINK_TEXT, "Журнал").click()
  time.sleep(3)
  wait = WebDriverWait(driver, 20)
  #table = wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, 'span#srv-time')))
  srv_time_element = wait.until(EC.visibility_of_element_located((By.ID, 'srv_time')))
  # Находим вложенный <span>
  time_span = srv_time_element.find_element(By.TAG_NAME, 'span')
  time_text = time_span.text
  timezone = time_text.split()[-1]
  if timezone == "+03:00":
    print("Часовой пояс указан верно")
  else:
    print("Часовой пояс указан не верно")
  time.sleep(3)
  driver.find_element(By.ID, "devlog_end_date").click()
  time.sleep(3)
  driver.find_element(By.ID, "devlog_end_date").send_keys("24.02.2025 15:00")
  driver.find_element(By.ID, "devlog_end_date").send_keys(Keys.ENTER)
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, ".nobr:nth-child(10) input").click()
  time.sleep(3)
  driver.find_element(By.NAME, "event_type").click()
  time.sleep(3)
  screenshot_paths.append(take_screenshot(driver, "11"))
  driver.find_element(By.CSS_SELECTOR, ".nobr:nth-child(1) > .enable-me-paramread").click()
  driver.find_element(By.CSS_SELECTOR, ".nobr:nth-child(2) > .enable-me-paramread").click()
  driver.find_element(By.CSS_SELECTOR, ".nobr:nth-child(3) > .enable-me-paramread").click()
  driver.find_element(By.CSS_SELECTOR, ".center > .ui-button").click()
  time.sleep(3)
  print("Вкладка 'Просмотр журнала событий':ОК")
except Exception as e:
    print("Вкладка 'Просмотр журнала событий':ERROR")
    
  #ПОСТРОЕНИЕ ГРАФИКОВ ВО ВКЛАДКЕ "ЖУРНАЛ"
try:
  driver.find_element(By.ID, "ui-id-10").click()
  time.sleep(3)
  dropdown = driver.find_element(By.ID, "device")
  dropdown.find_element(By.XPATH, "//option[. = '6 / engn-4.0.0 / QUASAR-TP']").click()
  time.sleep(3)
  element = driver.find_element(By.ID, "device")
  actions = ActionChains(driver)
  actions.move_to_element(element).release().perform()
  dropdown = driver.find_element(By.ID, "param")
  dropdown.find_element(By.XPATH, "//option[. = 'Ln1Pin']").click()
  time.sleep(3)
  element = driver.find_element(By.ID, "param")
  actions = ActionChains(driver)
  actions.move_to_element(element).release().perform()
  time.sleep(3)
  screenshot_paths.append(take_screenshot(driver, "14"))
  time.sleep(3)
  print("Вкладка 'Построение графиков':ОК")
except Exception as e:
    print("Вкладка 'Построение гарфиков':ERROR")
    
  #СПИСОК ЖУРНАЛОВ ВО ВКЛАДКЕ "ЖУРНАЛ" И ОТОБРАЖЕНИЕ ОДНОГО ИЗ НИХ
try:
  driver.find_element(By.ID, "ui-id-11").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, "#system_logs_form > .ui-widget-header").click()
  time.sleep(3)
  driver.find_element(By.LINK_TEXT, "apps.log").click()
  time.sleep(3)
  screenshot_paths.append(take_screenshot(driver, "16"))
  time.sleep(3)
  print("Вкладка 'Список журналов':ОК")
except Exception as e:
    print("Вкладка 'Список журналов':ERROR")
    
pdf_dir = 'output'
pdf_filename = os.path.join(pdf_dir, "screens_blade.pdf")  # Путь к PDF-файлу
create_pdf_from_images(screenshot_paths, pdf_filename)

driver.quit()
sys.stdout.close()
sys.stdout = sys.__stdout__